const data = {
    restaurants: {
      KFC: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
      McDonalds: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
      Hardees: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
      PizzaHut: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
      Subway: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
      BurgerKing: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
      BaskinRobbins: [
        "Burger Lab",
        "Johnny and Jugnu",
        "Smash Burger",
        "Howdy",
        "BRGR",
        "Sweet Creme",
        "Daily Deli",
        "OPTP",
      ],
    },
  
    cosmetics: {
      Loreal: ["J.", "Luscious Cosmetics", "Musarrat Misbah", "Rivaj"],
      Revlon: ["J.", "Luscious Cosmetics", "Musarrat Misbah", "Rivaj"],
      Garnier: ["J.", "Luscious Cosmetics", "Musarrat Misbah", "Rivaj"],
      EsteeLauder: ["J.", "Luscious Cosmetics", "Musarrat Misbah", "Rivaj"],
      Olay: ["J.", "Luscious Cosmetics", "Musarrat Misbah", "Rivaj"],
    },
  
    cold_drinks: {
      CocaCola: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      SevenUp: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      Fanta: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      Pepsi: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      Sprite: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      Mirinda: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      MountainDew: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      Roar: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
      Cappy: ["Gourmet Cola", "Gourmet Lemon Up", "Pakola", "Next Cola"],
    },
  
    chocolates: {
      Nutella: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Kitkat: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Mars: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Twix: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Snickers: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Toblerone: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Hersheys: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Milka: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      FerreroRocher: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Beuno: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
      Cadbury: [
        "Youngs Chocolate Spread",
        "Candyland Now",
        "Candyland Paradise",
        "Candyland Sonnet",
        "Candyland Novella",
        "You",
      ],
    },
  
    tea_coffee: {
      Lipton: ["Vital Tea", "National Tea", "ITC", "Tapal DaneDar"],
      NestleEverydayTea: ["Vital Tea", "National Tea", "ITC", "Tapal DaneDar"],
      NescafeCoffee: ["Vital Tea", "National Tea", "ITC", "Tapal DaneDar"],
    },
  
    juices: {
      NestleFruitaVitals: [
        "Fresher",
        "Fruitien",
        "Maza",
        "Vivo",
        "Sunsip LimoPani",
        "Rooh Afza",
        "Jami Shireen",
      ],
      NestleNesfruita: [
        "Fresher",
        "Fruitien",
        "Maza",
        "Vivo",
        "Sunsip LimoPani",
        "Rooh Afza",
        "Jami Shireen",
      ],
      Tang: [
        "Fresher",
        "Fruitien",
        "Maza",
        "Vivo",
        "Sunsip LimoPani",
        "Rooh Afza",
        "Jami Shireen",
      ],
      Slice: [
        "Fresher",
        "Fruitien",
        "Maza",
        "Vivo",
        "Sunsip LimoPani",
        "Rooh Afza",
        "Jami Shireen",
      ],
    },
  
    flavoured_drinks: {
      Milo: ["Dayfresh", "Shakarganj", "Pakola"],
      Nesquik: ["Dayfresh", "Shakarganj", "Pakola"],
    },
  
    dairy_products: {
      NestleMilkpak: [
        "Prema",
        "Anhaar",
        "Dayfresh",
        "Haleeb",
        "Good Milk",
        "Adams",
        "Nurpur",
        "Tarang",
        "Prema Yogurt",
        "Gourmet Yogurt",
        "Adams Cheese",
      ],
      NestleEveryday: [
        "Prema",
        "Anhaar",
        "Dayfresh",
        "Haleeb",
        "Good Milk",
        "Adams",
        "Nurpur",
        "Tarang",
        "Prema Yogurt",
        "Gourmet Yogurt",
        "Adams Cheese",
      ],
      NestleYogurt: [
        "Prema",
        "Anhaar",
        "Dayfresh",
        "Haleeb",
        "Good Milk",
        "Adams",
        "Nurpur",
        "Tarang",
        "Prema Yogurt",
        "Gourmet Yogurt",
        "Adams Cheese",
      ],
      Nesvita: [
        "Prema",
        "Anhaar",
        "Dayfresh",
        "Haleeb",
        "Good Milk",
        "Adams",
        "Nurpur",
        "Tarang",
        "Prema Yogurt",
        "Gourmet Yogurt",
        "Adams Cheese",
      ],
    },
  
    water: {
      Nestle: [
        "Gourmet",
        "Sufi",
        "Pakola",
        "Masafi",
        "Springley",
        "Al Habib",
        "al-kafeel of hasan industries",
      ],
      Aquafina: [
        "Gourmet",
        "Sufi",
        "Pakola",
        "Masafi",
        "Springley",
        "Al Habib",
        "al-kafeel of hasan industries",
      ],
      Dasani: [
        "Gourmet",
        "Sufi",
        "Pakola",
        "Masafi",
        "Springley",
        "Al Habib",
        "al-kafeel of hasan industries",
      ],
    },
  
    cereals: {
      NestleCocoCrunch: ["Nutri Lov Crunchy Cereal", "Fauji Cornflakes"],
      Kelloggs: ["Nutri Lov Crunchy Cereal", "Fauji Cornflakes"],
    },
  
    snacks: {
      Lays: ["Super Crisp", "Oye Hoye", "Kurleez", "Knock Out", "Kolson Snacks"],
      Cheetos: [
        "Super Crisp",
        "Oye Hoye",
        "Kurleez",
        "Knock Out",
        "Kolson Snacks",
      ],
      Kurkure: [
        "Super Crisp",
        "Oye Hoye",
        "Kurleez",
        "Knock Out",
        "Kolson Snacks",
      ],
      Pringles: [
        "Super Crisp",
        "Oye Hoye",
        "Kurleez",
        "Knock Out",
        "Kolson Snacks",
      ],
      Doritos: [
        "Super Crisp",
        "Oye Hoye",
        "Kurleez",
        "Knock Out",
        "Kolson Snacks",
      ],
      Munchies: [
        "Super Crisp",
        "Oye Hoye",
        "Kurleez",
        "Knock Out",
        "Kolson Snacks",
      ],
    },
  
    biscuits: {
      Prince: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      Tuc: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      Gala: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      ZeeraPlus: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      Bakeri: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      NanKhatai: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      Candi: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
      Oreo: [
        "Bisconni",
        "Whistlez",
        "Innovative",
        "EBM (English Biscuit Manufacturer)",
      ],
    },
  
    noodles_pasta: {
      Maggi: ["Kolson Pasta", "National Pasta", "Shoop by Shan"],
      Knorr: ["Kolson Pasta", "National Pasta", "Shoop by Shan"],
    },
  
    iced_tea: {
      Nestea: ["Tapal Ice Tea"],
      Fuzetea: ["Tapal Ice Tea"],
    },
  
    shampoos: {
      Dove: [
        "Saeed Ghani Shampoo",
        "CoNatural Shampoo",
        "BioAmla Shampoo",
        "Jasmine Organics Shampoo bar",
      ],
      Sunsilk: [
        "Saeed Ghani Shampoo",
        "CoNatural Shampoo",
        "BioAmla Shampoo",
        "Jasmine Organics Shampoo bar",
      ],
      Pantene: [
        "Saeed Ghani Shampoo",
        "CoNatural Shampoo",
        "BioAmla Shampoo",
        "Jasmine Organics Shampoo bar",
      ],
      HeadAndShoulders: [
        "Saeed Ghani Shampoo",
        "CoNatural Shampoo",
        "BioAmla Shampoo",
        "Jasmine Organics Shampoo bar",
      ],
      Clear: [
        "Saeed Ghani Shampoo",
        "CoNatural Shampoo",
        "BioAmla Shampoo",
        "Jasmine Organics Shampoo bar",
      ],
      Tresemme: [
        "Saeed Ghani Shampoo",
        "CoNatural Shampoo",
        "BioAmla Shampoo",
        "Jasmine Organics Shampoo bar",
      ],
    },
  
    toothpaste: {
      Colgate: ["Medicam", "Dentonic", "Jasmine Organics Herbal tooth powder"],
      Sensodyne: ["Medicam", "Dentonic", "Jasmine Organics Herbal tooth powder"],
    },
  
    body_care: {
      Lux: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
      Dove: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
      Lifebuoy: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
      Ponds: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
      FairAndGlow: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
      Gilette: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
      Veet: [
        "Care soap",
        "Vital Soap",
        "Nisa Hair Removal Cream",
        "Hiba Hair Removal",
        "Treet",
        "Saeed Ghani Lotion",
        "Jasmine Organics moisturiser",
      ],
    },
  
    sanitary_napkins: {
      Always: ["Butterfly", "Mother Comfort", "Trust"],
    },
  
    babycare: {
      Johnsons: ["Sheild Babycare", "Leo Diapers"],
      Pampers: ["Sheild Babycare", "Leo Diapers"],
      Huggies: ["Sheild Babycare", "Leo Diapers"],
    },
  
    detergents: {
      SurfExcel: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Ariel: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Bonus: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Bright: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Express: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Vim: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Max: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
      Sunlight: [
        "Sufi Detergent",
        "Sufi Liquid Dishsoap",
        "Alclean all purpose cleaner",
        "Almas dishwashe",
      ],
    },
  };
  
  export default data;
  